In [ ]:
# Task 1 — Create a Tensor
# Create a 1D tensor containing the following sensor readings:
# 25.2, 25.5, 24.9, 26.1, 25.8
# Perform the following:
# 1.	Print the tensor. 
# 2.	Print its shape. 
# 3.	Print the number of dimensions. 
# 4.	Print the number of elements. 
# The goal is to make to all remember the  difference between tensor values, shape, size, and number of dimensions.

In [1]:
import torch

sensor_readings = torch.tensor([25.2, 25.5, 24.9, 26.1, 25.8])


print("Tensor values:", sensor_readings)


print("Shape:", sensor_readings.shape)


print("Number of dimensions:", sensor_readings.ndim)


print("Number of elements:", sensor_readings.numel())


Tensor values: tensor([25.2000, 25.5000, 24.9000, 26.1000, 25.8000])
Shape: torch.Size([5])
Number of dimensions: 1
Number of elements: 5


In [ ]:
# Task 2 — From Vector to Matrix
# Suppose an industrial system has 4 sensors recording measurements for 5 time steps.
# Create the following data:
# Temperature:  [25, 26, 25, 27, 28]
# Pressure:     [101, 102, 101, 103, 104]
# Humidity:     [60, 62, 61, 63, 64]
# Vibration:    [0.2, 0.3, 0.2, 0.4, 0.5]
# Create a tensor with shape:
# (5, 4)
# where:
# rows    → time
# columns → sensors

# Then print:
# •	shape 
# •	number of dimensions 
# •	first time step 
# •	temperature readings 
# •	vibration readings 
# Think: What does each axis represent?



In [2]:
import torch


temperature = [25, 26, 25, 27, 28]
pressure    = [101, 102, 101, 103, 104]
humidity    = [60, 62, 61, 63, 64]
vibration   = [0.2, 0.3, 0.2, 0.4, 0.5]


data = torch.tensor([
    [25, 101, 60, 0.2],
    [26, 102, 62, 0.3],
    [25, 101, 61, 0.2],
    [27, 103, 63, 0.4],
    [28, 104, 64, 0.5]
])


print("Shape:", data.shape)               
print("Number of dimensions:", data.ndim) 
print("First time step:", data[0])        
print("Temperature readings:", data[:,0])  
print("Vibration readings:", data[:,3])   


Shape: torch.Size([5, 4])
Number of dimensions: 2
First time step: tensor([ 25.0000, 101.0000,  60.0000,   0.2000])
Temperature readings: tensor([25., 26., 25., 27., 28.])
Vibration readings: tensor([0.2000, 0.3000, 0.2000, 0.4000, 0.5000])


In [ ]:
# Task 3 — Create a 3D Tensor
# Now suppose we monitor 10 machines.
# Each machine has:
# •	5 time steps 
# •	4 sensors 
# Create a tensor with shape:
# (10, 5, 4)
# Interpret the dimensions as:
# Machine × Time × Sensor
# Then answer using Python:
# 1.	What is the temperature reading of machine 3 at time step 2? 
# 2.	Extract all sensor readings of machine 5. 
# 3.	Extract all machines at time step 1. 
# 4.	Extract the readings of sensor 4 from all machines and all time steps. 


In [3]:
import torch


data = torch.rand((10, 5, 4))  
temp_m3_t2 = data[2, 1, 0]
print("Temperature of machine 3 at time step 2:", temp_m3_t2)

machine5_readings = data[4]
print("All sensor readings of machine 5:\n", machine5_readings)

time1_all_machines = data[:, 0, :]
print("All machines at time step 1:\n", time1_all_machines)


sensor4_all = data[:, :, 3]
print("Sensor 4 readings across all machines and time steps:\n", sensor4_all)


Temperature of machine 3 at time step 2: tensor(0.9708)
All sensor readings of machine 5:
 tensor([[0.0975, 0.8260, 0.4470, 0.7962],
        [0.5734, 0.3669, 0.4308, 0.8597],
        [0.6968, 0.8693, 0.8104, 0.3816],
        [0.6772, 0.8265, 0.2524, 0.3108],
        [0.6092, 0.8109, 0.8525, 0.6804]])
All machines at time step 1:
 tensor([[0.9408, 0.6116, 0.7740, 0.3981],
        [0.4461, 0.5284, 0.9427, 0.8320],
        [0.3945, 0.3042, 0.5081, 0.2634],
        [0.3747, 0.4865, 0.4782, 0.2567],
        [0.0975, 0.8260, 0.4470, 0.7962],
        [0.1696, 0.3043, 0.8886, 0.2382],
        [0.9739, 0.4446, 0.9400, 0.4005],
        [0.9180, 0.3370, 0.1537, 0.0247],
        [0.3151, 0.8985, 0.4966, 0.7410],
        [0.9771, 0.1906, 0.8255, 0.7817]])
Sensor 4 readings across all machines and time steps:
 tensor([[0.3981, 0.7872, 0.4815, 0.4721, 0.8143],
        [0.8320, 0.5693, 0.4472, 0.0608, 0.0360],
        [0.2634, 0.9867, 0.7978, 0.7819, 0.2198],
        [0.2567, 0.0504, 0.2778, 0.7289, 0

In [ ]:
# Task 4 — Indexing a Tensor
# Create:
# X = np.arange(24).reshape(2, 3, 4)
# Print X.
# Now investigate:
# X[0]
# X[1]
# X[0, 0]
# X[0, 0, 0]

# Answer:
# 1.	What is the shape of X? 
# 2.	What does X[0] represent? 
# 3.	What does X[0,0] represent? 
# 4.	What does X[0,0,0] represent? 


In [5]:
import numpy as np

X = np.arange(24).reshape(2, 3, 4)

print(X)
print(X[0])
print(X[1])
print(X[0, 0])
print(X[0, 0, 0])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[0 1 2 3]
0


In [ ]:
# Task 5 — Slicing
# Using:
# X = np.arange(60).reshape(3, 4, 5)
# Perform:
# •	Extract the first block: X[0]
# •	Extract the first row from every block.
# •	Extract the third element from every row and every block.
# •	Extract the last two elements along the final dimension. Then print the resulting shapes.


In [9]:
import numpy as np
X2 = np.arange(60).reshape(3, 4, 5)

print(X2[0])
print(X2[:, :1])
print(X2[:, :, :2])

result = X2[:, :, -2:]

print("Shape before:", X2.shape)   
print("Shape after:", result.shape) 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[[ 0  1  2  3  4]]

 [[20 21 22 23 24]]

 [[40 41 42 43 44]]]
[[[ 0  1]
  [ 5  6]
  [10 11]
  [15 16]]

 [[20 21]
  [25 26]
  [30 31]
  [35 36]]

 [[40 41]
  [45 46]
  [50 51]
  [55 56]]]
Shape before: (3, 4, 5)
Shape after: (3, 4, 2)


In [ ]:
# Task 6 — Image Tensor
# Create a synthetic RGB image tensor:
# Height = 128
# Width = 128
# Channels = 3
# Create:
# image = ...
# with shape: (128, 128, 3)
# Then:
# 1.	Print the shape. 
# 2.	Extract the red channel. 
# 3.	Extract the green channel. 
# 4.	Extract the blue channel. 
# 5.	Find the maximum pixel value. 
# 6.	Find the minimum pixel value. 


In [10]:
import numpy as np

image = np.random.randint(0, 256, size=(128, 128, 3), dtype=np.uint8)

print("Shape:", image.shape)

red_channel = image[:, :, 0]
print("Red channel shape:", red_channel.shape)

green_channel = image[:, :, 1]
print("Green channel shape:", green_channel.shape)

blue_channel = image[:, :, 2]
print("Blue channel shape:", blue_channel.shape)

print("Max pixel value:", image.max())

print("Min pixel value:", image.min())


Shape: (128, 128, 3)
Red channel shape: (128, 128)
Green channel shape: (128, 128)
Blue channel shape: (128, 128)
Max pixel value: 255
Min pixel value: 0


In [ ]:
# Task 7 — Batch of Images
# Now suppose you have 32 RGB images, each of size 128 × 128.
# Create a tensor with shape:
# (32, 128, 128, 3)
# using random values.
# Then:
# 1.	Extract the first image. 
# 2.	Extract the first 10 images. 
# 3.	Extract the red channel from all images. 
# 4.	Extract pixel (50, 50) from every image. 
# 5.	Print the shape after each operation. 


In [11]:
import numpy as np

images = np.random.randint(0, 256, size=(32, 128, 128, 3), dtype=np.uint8)

first_image = images[0]
print("First image shape:", first_image.shape)   # (128, 128, 3)

first_10_images = images[:10]
print("First 10 images shape:", first_10_images.shape)   # (10, 128, 128, 3)

red_channel = images[:, :, :, 0]
print("Red channel shape:", red_channel.shape)   # (32, 128, 128)

pixel_50_50 = images[:, 50, 50, :]
print("Pixel (50,50) from all images shape:", pixel_50_50.shape)   # (32, 3)



First image shape: (128, 128, 3)
First 10 images shape: (10, 128, 128, 3)
Red channel shape: (32, 128, 128)
Pixel (50,50) from all images shape: (32, 3)


In [ ]:
# Task 8 — Reshape
# Create:
# X = np.arange(24)
# Reshape it into:
# (4, 6)
# (2, 3, 4)
# (6, 4)
# (24,)
# For each one:
# 1.	Print the tensor. 
# 2.	Print its shape. 
# 3.	Print its number of dimensions. 
# Then try answering:
# Why does reshaping change the shape but not the total number of elements?


In [12]:
import numpy as np

# Create the base array
X3 = np.arange(24)

# Reshape into different forms
shapes = [(4, 6), (2, 3, 4), (6, 4), (24,)]

for s in shapes:
    arr = X3.reshape(s)
    print("Reshaped to:", s)
    print(arr)
    print("Shape:", arr.shape)
    print("Number of dimensions:", arr.ndim)
  

Reshaped to: (4, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Shape: (4, 6)
Number of dimensions: 2
Reshaped to: (2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Shape: (2, 3, 4)
Number of dimensions: 3
Reshaped to: (6, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Shape: (6, 4)
Number of dimensions: 2
Reshaped to: (24,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Shape: (24,)
Number of dimensions: 1


In [ ]:
# Task 9 — Reshape vs Transpose
# Create:
# X = np.arange(24).reshape(2, 3, 4)
# Now perform:
# X.reshape(3, 2, 4) and X.transpose(1, 0, 2)
# Compare the results.
# Are these two operations doing the same thing?


In [13]:
import numpy as np

X3 = np.arange(24).reshape(2, 3, 4)

reshaped = X3.reshape(3, 2, 4)

transposed = X3.transpose(1, 0, 2)

print("Original shape:", X3.shape)
print("Reshape (3,2,4):", reshaped.shape)
print("Transpose (1,0,2):", transposed.shape)

print("\nReshape result:\n", reshaped)
print("\nTranspose result:\n", transposed)


Original shape: (2, 3, 4)
Reshape (3,2,4): (3, 2, 4)
Transpose (1,0,2): (3, 2, 4)

Reshape result:
 [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]

Transpose result:
 [[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]


In [ ]:
# Task 10 — Broadcasting
# Create:
# X = np.ones((3, 4))
# and:
# b = np.array([10, 20, 30, 40])
# Calculate: X + b
# Then try: X * b
# Question: Why can a (4,) tensor be combined with a (3,4) tensor?


In [14]:
import numpy as np

A = np.ones((3, 4))          
b = np.array([10, 20, 30, 40]) 

print("A:\n", A)
print("b:\n", b)

print("\nA + b:\n", A + b)
print("\nA * b:\n", A * b)
#NumPy treats (4,) as (1,4) and automatically repeats it across the 3 rows, so the shapes align

A:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
b:
 [10 20 30 40]

A + b:
 [[11. 21. 31. 41.]
 [11. 21. 31. 41.]
 [11. 21. 31. 41.]]

A * b:
 [[10. 20. 30. 40.]
 [10. 20. 30. 40.]
 [10. 20. 30. 40.]]


In [ ]:
# Task 11 — Broadcasting with Sensor Data
# Suppose:
# X.shape = (100, 10)
# represents:
# 100 samples × 10 sensors
# The calibration offset for each sensor is:
# [1.2, 0.8, 1.1, 0.5, 0.9, 1.0, 0.7, 1.3, 0.6, 0.4]
# Create the tensor and subtract the calibration offsets.
# Your output should remain:
# (100, 10)
# Goal: See broadcasting in an actual engineering problem.


In [15]:
import numpy as np

X4 = np.random.randn(100, 10)   

offsets = np.array([1.2, 0.8, 1.1, 0.5, 0.9, 1.0, 0.7, 1.3, 0.6, 0.4])

# Subtract calibration offsets
X_calibrated = X4 - offsets

print("Shape before:", X4.shape)
print("Shape after:", X_calibrated.shape)


Shape before: (100, 10)
Shape after: (100, 10)


In [ ]:
# Task 12 — Tensor Aggregation
# Create:
# X = np.random.randn(100, 20, 5)
# Interpret it as:
# 100 machines
# 20 time steps
# 5 sensors
# Calculate:
# 1.	Mean across time. 
# 2.	Mean across sensors. 
# 3.	Mean across machines. 
# 4.	Maximum sensor value across time. 
# 5.	Standard deviation across time. 
# Predict the resulting shape before running the code.


In [16]:
import numpy as np

Y = np.random.randn(100, 20, 5)

# 1. Mean across time (axis=1)
mean_time = Y.mean(axis=1)

# 2. Mean across sensors (axis=2)
mean_sensors = Y.mean(axis=2)

# 3. Mean across machines (axis=0)
mean_machines = Y.mean(axis=0)

# 4. Maximum sensor value across time (axis=1)
max_sensor_time = Y.max(axis=1)

# 5. Standard deviation across time (axis=1)
std_time = Y.std(axis=1)

print("Mean across time:", mean_time.shape)
print("Mean across sensors:", mean_sensors.shape)
print("Mean across machines:", mean_machines.shape)
print("Max sensor value across time:", max_sensor_time.shape)
print("Std across time:", std_time.shape)


Mean across time: (100, 5)
Mean across sensors: (100, 20)
Mean across machines: (20, 5)
Max sensor value across time: (100, 5)
Std across time: (100, 5)


In [ ]:
# Task 13 — Normalize a Tensor
# Create sensor data:
# X = np.random.randn(100, 20, 5)
# Calculate the mean and standard deviation for each sensor.
# Normalize the tensor using:
# Then verify:
# mean ≈ 0
# standard deviation ≈ 1


In [17]:
import numpy as np

X = np.random.randn(100, 20, 5)

mu = X.mean(axis=(0,1))        
sigma = X.std(axis=(0,1))      

X_normalized = (X - mu) / sigma

print("Shape:", X_normalized.shape)        
print("Mean (per sensor):", X_normalized.mean(axis=(0,1)))  
print("Std (per sensor):", X_normalized.std(axis=(0,1)))    


Shape: (100, 20, 5)
Mean (per sensor): [ 2.40363285e-17  7.60225216e-17 -1.09245946e-16  6.99995617e-17
 -6.60582700e-18]
Std (per sensor): [1. 1. 1. 1. 1.]


In [ ]:
# Task 14 — Flattening
# Create an image:
# (28, 28, 3)
# Flatten it into:
# (2352,)
# Then create a batch of 64 images:
# (64, 28, 28, 3)
# Flatten each image while keeping the batch dimension.
# Expected shape: 	(64, 2352)
# Why shouldn't we simply flatten the entire tensor into (150528,) when working with a batch?


In [18]:
import numpy as np


img = np.random.randn(28, 28, 3)
flat_img = img.reshape(-1)   
print("Single image flattened:", flat_img.shape)

batch = np.random.randn(64, 28, 28, 3)
flat_batch = batch.reshape(64, -1)   
print("Batch flattened:", flat_batch.shape)


Single image flattened: (2352,)
Batch flattened: (64, 2352)


In [ ]:
# Task 15 — Concatenation
# Suppose a model produces two feature tensors:
# Visual features:
# (32, 128)

# Sensor features:
# (32, 64)
# Combine them into a single feature tensor.
# Expected result:
# (32, 192)
# Use tensor concatenation.
# Then explain:
# Why can we concatenate along the feature dimension but not arbitrarily along every dimension?


In [19]:
import numpy as np

visual = np.random.randn(32, 128)

sensor = np.random.randn(32, 64)

combined = np.concatenate([visual, sensor], axis=1)

print("Combined shape:", combined.shape)


Combined shape: (32, 192)


In [ ]:
# Task 16 — Practical Mini Challenge: Sensor Dataset
# Create a synthetic dataset representing:
# 500 machines
# 60 time steps
# 8 sensors

# Therefore:

# X.shape = (500, 60, 8)

# Perform the following:
# 1.	Extract machine 10. 
# 2.	Extract the first 20 time steps. 
# 3.	Extract sensor 5 from all machines. 
# 4.	Calculate the average value of every sensor. 
# 5.	Calculate the average value at every time step. 
# 6.	Find the machine with the highest average sensor reading. 
# 7.	Normalize each sensor. 
# 8.	Split the tensor into: 
# o	Training: 400 machines 
# o	Testing: 100 machines 



In [20]:
import numpy as np

X5 = np.random.randn(500, 60, 8)

print(X5[9])
print(X5[:, :20, :])
print(X5[:, :, 4])
print(X5.mean(axis=(0,1)))
print(X5.mean(axis=(0,2)))
machine_means = X5.mean(axis=(1,2))
print(np.argmax(machine_means))

mu = X5.mean(axis=(0,1))

sigma = X5.std(axis=(0,1))

X_norm = (X5 - mu) / sigma

X_train = X[:400]

X_test = X[400:]

[[-0.10444968 -0.6575124  -0.13140966 -0.06162804  1.26375664 -1.45658401
   0.84822965  0.31494828]
 [ 0.34512078 -0.88533075 -0.63956298  0.80891716  0.54013549 -0.57469252
  -0.63897156 -1.6151704 ]
 [ 0.29720877  1.82559555 -0.40376529  0.40988173  0.43234209  0.12921106
  -0.03742433  1.16115897]
 [-0.26338932  0.49784967  1.09635348  1.60742495  0.53234704  0.86389962
  -1.17647487 -0.24255808]
 [-0.51435309  0.28800035  0.73698137  0.9703578   0.40496259 -0.10316661
  -1.13996707  1.61670858]
 [-0.62622533  0.44560406  0.1357408   1.48334265  0.16262269  1.68428721
   0.59656941 -0.94512241]
 [-0.84555815  0.85358055 -1.70002691 -0.35675857  0.49654044  1.24795873
  -0.06569316 -1.12396006]
 [-1.00962239  0.01983153  0.07654591  1.46834024 -1.05865121  1.8732377
  -1.3011914  -0.76426647]
 [-0.42220912 -1.35272263  0.41489991  0.25590789  0.45111559  0.44865608
  -1.41693858  0.91133376]
 [-0.25614643 -0.64229226 -0.21555789  2.40104966  1.15861166  1.96118562
   0.55429711  0.0

In [ ]:
# Task 17 — PyTorch 

# import torch
# X = torch.arange(24).reshape(2, 3, 4)

# print(X)
# print(X.shape)
# print(X.ndim)
# print(X.numel())

# Then try:
# X = torch.randn(32, 100, 768)

# What could these three dimensions represent?





In [ ]:
import torch

X6 = torch.arange(24).reshape(2, 3, 4)

print(X6)
print("Shape:", X6.shape)   
print("Dimensions:", X6.ndim)  
print("Number of elements:", X6.numel())  

X6 = torch.randn(32, 100, 768)
print("Shape:", X6.shape)
